# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Mopcon' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Mopcon
    pod 'Kingfisher'
    pod 'Firebase/Core'
    pod 'Firebase/Messaging'
    pod 'Firebase/DynamicLinks'
    pod 'Firebase/InAppMessaging'
#    pod 'Firebase/RemoteConfig'
end
